ALTER TABLE "CUST_DATA" RENAME TO 'CUST_DATA_TEMP_TPSODL';
CREATE TABLE "CUST_DATA" ( 
"USER_ID" TEXT,
"DIVISION_CODE" TEXT,
"CONS_ACC" TEXT, 
"CUST_ID" TEXT, 
"DIVISION" TEXT, 
"SUBDIVISION" TEXT, 
"SECTION" TEXT, 
"CON_NAME" TEXT, 
"CON_ADD1" TEXT, 
"CON_ADD2" TEXT, 
"PRSN_KWH" TEXT, 
"CUR_TOTAL" TEXT, 
"BILL_TOTAL" TEXT, 
"REBATE" TEXT, 
"DUE_DATE" TEXT, 
"MOBILE_NO" TEXT, 
"EMAIL" TEXT, 
"PAY_CNT" TEXT  );
INSERT INTO "CUST_DATA" ("USER_ID", "DIVISION_CODE", "CONS_ACC", "CUST_ID", "DIVISION", "SUBDIVISION", "SECTION", "CON_NAME", "CON_ADD1", "CON_ADD2", "PRSN_KWH", "CUR_TOTAL", "BILL_TOTAL" , "REBATE", "DUE_DATE", "MOBILE_NO", "EMAIL") SELECT "USER_ID", "DIVISION_CODE", "CONS_ACC", "CUST_ID", "DIVISION", "SUBDIVISION", "SECTION", "CON_NAME", "CON_ADD1", "CON_ADD2", "PRSN_KWH", "CUR_TOTAL", "BILL_TOTAL" , "REBATE", "DUE_DATE", "MOBILE_NO", "EMAIL" FROM "CUST_DATA_TEMP_TPSODL";
DROP TABLE "CUST_DATA_TEMP_TPSODL";
