CREATE  TABLE "NONENERGY_DATA"
(
"USER_ID" TEXT,
"COMPANY_CODE" TEXT,
"SCNO" TEXT,
"REF_MODULE" TEXT,
"REF_REG_NO" TEXT,
"CUST_ID" TEXT,
"DIVISION" TEXT,
"SUBDIVISION" TEXT,
"SECTION" TEXT,
"CON_NAME" TEXT,
"CON_ADD1" TEXT,
"CON_ADD2" TEXT,
"AMOUNT" TEXT,
"DEMAND_DATE" TEXT,
"MOBILE_NO" TEXT,
"EMAIL" TEXT,
"REMARKS" TEXT,
"FIELD1" TEXT,
"FIELD2" TEXT,
"FIELD3" TEXT,
"FIELD4" TEXT,
"FIELD5" TEXT,
"ENTRYDATE" TEXT
);


CREATE  TABLE "COLL_NEN_DATA"
(
"USER_ID" TEXT,
"COMPANY_CODE" TEXT,
"SCNO" TEXT,
"REF_MODULE" TEXT,
"REF_REG_NO" TEXT,
"CUST_ID" TEXT,
"DIVISION" TEXT,
"SUBDIVISION" TEXT,
"SECTION" TEXT,
"CON_NAME" TEXT,
"CON_ADD1" TEXT,
"AMOUNT" TEXT,
"DEMAND_DATE" TEXT,
"MOBILE_NO" TEXT,
"EMAIL" TEXT,
"RECPT_DATE"	DATE,
"RECPT_TIME"	varchar,
"MR_No"	varchar,
"MACHINE_NO"	varchar,
"TOT_PAID"	NUMBER,
"PAY_MODE"	NUMBER,
"RECPT_FLG"	NUMBER,
"OPERATOR_ID"	NUMBER,
"OPERATOR_NAME"	varchar,
"SEND_FLG"	NUMBER,
"COLL_FLG"	NUMBER,
"TRANS_ID"	NUMBER,
"PMT_TYP"	varchar,
"TRANS_DATE"	DATE,
"BAL_FETCH"	NUMBER(16, 2),
"OPERATION_TYPE"	TEXT,
"LATTITUDE"	TEXT,
"LONGITUDE"	TEXT,  
"REMARKS" TEXT,
"FIELD1" TEXT,
"FIELD2" TEXT,
"FIELD3" TEXT,
"FIELD4" TEXT,
"FIELD5" TEXT,
"ENTRYDATE" TEXT
);

CREATE  TABLE "COLL_NEN_DATA_BKP"
(
"USER_ID" TEXT,
"COMPANY_CODE" TEXT,
"SCNO" TEXT,
"REF_MODULE" TEXT,
"REF_REG_NO" TEXT,
"CUST_ID" TEXT,
"DIVISION" TEXT,
"SUBDIVISION" TEXT,
"SECTION" TEXT,
"CON_NAME" TEXT,
"CON_ADD1" TEXT,
"AMOUNT" TEXT,
"DEMAND_DATE" TEXT,
"MOBILE_NO" TEXT,
"EMAIL" TEXT,
"RECPT_DATE"	DATE,
"RECPT_TIME"	varchar,
"MR_No"	varchar,
"MACHINE_NO"	varchar,
"TOT_PAID"	NUMBER,
"PAY_MODE"	NUMBER,
"RECPT_FLG"	NUMBER,
"OPERATOR_ID"	NUMBER,
"OPERATOR_NAME"	varchar,
"SEND_FLG"	NUMBER,
"COLL_FLG"	NUMBER,
"TRANS_ID"	NUMBER,
"PMT_TYP"	varchar,
"TRANS_DATE"	DATE,
"BAL_FETCH"	NUMBER(16, 2),
"OPERATION_TYPE"	TEXT,
"LATTITUDE"	TEXT,
"LONGITUDE"	TEXT,
"REMARKS" TEXT,
"FIELD1" TEXT,
"FIELD2" TEXT,
"FIELD3" TEXT,
"FIELD4" TEXT,
"FIELD5" TEXT,
"ENTRYDATE" TEXT
);

ALTER TABLE "SA_User" RENAME TO 'SA_User_TEMP_TPWODL';
CREATE TABLE "SA_User" (
"Userid" TEXT,
"passkey" TEXT,
"valid_startdate" NUMBER,
"valid_enddate" NUMBER,
"Lock_Flag" NUMBER,
"retries" NUMBER,
"user_name" TEXT,
"user_description" TEXT,
"prv_flg" TEXT,
"Office_Code" TEXT,
"Coll_Limit" NUMBER,
"Tot_Mr" NUMBER,
"Indv_Collection" NUMBER,
"Max_Date" NUMBER,
"Session_time" TEXT,
"Bal_Remain" NUMBER,
"session_duration" TEXT,
"Login_Time" TEXT,
"Company_ID" INTEGER,
"prv_bill" INTEGER,
"SBMPRV" NUMBER,
"energy_flag" TEXT,
"non_energy_flag" TEXT,
"NSC_flag" TEXT,
"CSC_flag" TEXT,
"DND_flag" TEXT,
"FRM_flag" TEXT,
"one_flag" TEXT,
"two_flag" TEXT,
"three_flag" TEXT,
"four_flag" TEXT  );
INSERT INTO "SA_User" ("Userid","passkey","valid_startdate","valid_enddate","Lock_Flag","retries","user_name","user_description","prv_flg","Office_Code","Coll_Limit","Tot_Mr","Indv_Collection","Max_Date","Session_time","Bal_Remain","session_duration","Login_Time","Company_ID","prv_bill","SBMPRV") SELECT "Userid","passkey","valid_startdate","valid_enddate","Lock_Flag","retries","user_name","user_description","prv_flg","Office_Code","Coll_Limit","Tot_Mr","Indv_Collection","Max_Date","Session_time","Bal_Remain","session_duration","Login_Time","Company_ID","prv_bill","SBMPRV" FROM "SA_User_TEMP_TPWODL";
DROP TABLE "SA_User_TEMP_TPWODL";
